# SPDX-License-Identifier: GPL-2.0-only
#
# Rockchip Soc drivers
#
obj-y += fiq_debugger/
obj-$(CONFIG_ROCKCHIP_GRF) += grf.o
obj-$(CONFIG_ROCKCHIP_IODOMAIN) += io-domain.o
obj-$(CONFIG_ROCKCHIP_DTPM) += dtpm.o
obj-$(CONFIG_FIQ_DEBUGGER) += rk_fiq_debugger.o
